spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: myoldfycy318@126.com
          uri: https://github.com/myoldfycy318/SpringcloudConfig
          password: 1qaz@WSX
          search-paths: config
      label: master
server:
  port: 8888


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

